### ISSUE TITLE
Creating a custom 404 Page, currently it shows Github 404 page

### ISSUE THREAD

**Issue by idontknowjs** [dscmsit/dscmsit.github.io#12]
This might help : https://help.github.com/articles/custom-404-pages
Tl;dr just name it as 404.html in root directory

![image](https://user-images.githubusercontent.com/53327173/97037393-dcd9e300-1586-11eb-8a6e-12bc8f5fbc43.png)

**Comment by hyunjiLeeTech** [comment]
Hi, can you please assign me to this issue?

**Comment by idontknowjs** [comment]
@hyunjiLeeTech someone is currently working on this, you can look for other issues
